// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/private-valeting/ModernLanding.tsx": () => import("../components/mockups/private-valeting/ModernLanding.tsx"),
  "./components/mockups/private-valeting/PremiumCards.tsx": () => import("../components/mockups/private-valeting/PremiumCards.tsx"),
  "./components/mockups/services-section/DarkCards.tsx": () => import("../components/mockups/services-section/DarkCards.tsx"),
  "./components/mockups/services-section/IconGrid.tsx": () => import("../components/mockups/services-section/IconGrid.tsx"),
  "./components/mockups/services-section/ListColumns.tsx": () => import("../components/mockups/services-section/ListColumns.tsx")
};
